#!/usr/bin/env bash
set -euo pipefail

if [[ -z "${POSTGRES_DB:-}" ]]; then
  echo "POSTGRES_DB is required" >&2
  exit 1
fi

QS_DB_MIGRATE_USER="${QS_DB_MIGRATE_USER:-qs_migrate}"
QS_DB_RUNTIME_USER="${QS_DB_RUNTIME_USER:-qs_runtime}"
QS_DB_BACKOFFICE_USER="${QS_DB_BACKOFFICE_USER:-qs_backoffice}"

if [[ -z "${QS_DB_MIGRATE_PASSWORD:-}" || -z "${QS_DB_RUNTIME_PASSWORD:-}" || -z "${QS_DB_BACKOFFICE_PASSWORD:-}" ]]; then
  echo "QS_DB_MIGRATE_PASSWORD, QS_DB_RUNTIME_PASSWORD and QS_DB_BACKOFFICE_PASSWORD are required" >&2
  exit 1
fi

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${QS_DB_MIGRATE_USER}') THEN
    -- IMPORTANT: The migrations role bypasses RLS and is intended ONLY for schema migrations
    -- and test/CI cleanup. Never use this role for application runtime credentials.
    CREATE ROLE ${QS_DB_MIGRATE_USER} LOGIN PASSWORD '${QS_DB_MIGRATE_PASSWORD}' BYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${QS_DB_RUNTIME_USER}') THEN
    CREATE ROLE ${QS_DB_RUNTIME_USER} LOGIN PASSWORD '${QS_DB_RUNTIME_PASSWORD}';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${QS_DB_BACKOFFICE_USER}') THEN
    CREATE ROLE ${QS_DB_BACKOFFICE_USER} LOGIN PASSWORD '${QS_DB_BACKOFFICE_PASSWORD}' BYPASSRLS;
  END IF;
END
\$\$;

-- Harden role attributes explicitly (idempotent).
ALTER ROLE ${QS_DB_MIGRATE_USER} BYPASSRLS NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
ALTER ROLE ${QS_DB_RUNTIME_USER} NOBYPASSRLS NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;
ALTER ROLE ${QS_DB_BACKOFFICE_USER} BYPASSRLS NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION;

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${QS_DB_MIGRATE_USER};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${QS_DB_RUNTIME_USER};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${QS_DB_BACKOFFICE_USER};
GRANT CREATE ON DATABASE ${POSTGRES_DB} TO ${QS_DB_MIGRATE_USER};

GRANT USAGE, CREATE ON SCHEMA public TO ${QS_DB_MIGRATE_USER};
GRANT USAGE ON SCHEMA public TO ${QS_DB_RUNTIME_USER};
GRANT USAGE ON SCHEMA public TO ${QS_DB_BACKOFFICE_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${QS_DB_MIGRATE_USER} IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${QS_DB_RUNTIME_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${QS_DB_MIGRATE_USER} IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO ${QS_DB_RUNTIME_USER};

-- NOTE: qs_backoffice does NOT get default privileges on tables.
-- All table access is granted explicitly in the Drizzle migration
-- (0038_backoffice_role_separation.sql) to enforce least-privilege.
SQL
