/**
 * MCE SQL constants for syntax highlighting and linting.
 * Aligns with MCE-SQL-REFERENCE.md to prevent drift between highlighting and linting.
 */

export const MCE_SQL_KEYWORDS = new Set([
  // Statement
  "select",
  // Clauses
  "from",
  "where",
  "join",
  "on",
  "group",
  "by",
  "having",
  "order",
  "union",
  "all",
  "intersect",
  "except",
  "distinct",
  "top",
  // JOIN variants
  "inner",
  "left",
  "right",
  "full",
  "outer",
  "cross",
  // Ordering
  "asc",
  "desc",
  // Alias
  "as",
  // Predicates/operators
  "and",
  "or",
  "not",
  "like",
  "in",
  "between",
  "exists",
  "is",
  "null",
  // OFFSET/FETCH (supported with ORDER BY)
  "offset",
  "fetch",
  "next",
  "first",
  "rows",
  "row",
  "only",
  // Control flow expressions
  "case",
  "when",
  "then",
  "else",
  "end",
  // GROUP BY extensions
  "rollup",
  "cube",
  // AT TIME ZONE
  "at",
  "time",
  "zone",
]);

export const MCE_SQL_PROHIBITED_DML = new Set([
  "insert",
  "update",
  "delete",
  "merge",
  "truncate",
]);

export const MCE_SQL_PROHIBITED_DDL = new Set([
  "drop",
  "alter",
  "create",
  "grant",
  "revoke",
  "commit",
  "rollback",
  "savepoint",
  "cursor",
  "open",
  "close",
  "deallocate",
  "backup",
  "restore",
  "kill",
  "go",
  "waitfor",
]);

export const MCE_SQL_PROHIBITED_PROCEDURAL = new Set([
  "declare",
  "set",
  "while",
  "if",
  "begin",
  "exec",
  "execute",
  "print",
  "raiserror",
  "throw",
  "try",
  "catch",
  "goto",
  "return",
  "break",
  "continue",
]);

export const MCE_SQL_ALL_PROHIBITED = new Set([
  ...MCE_SQL_PROHIBITED_DML,
  ...MCE_SQL_PROHIBITED_DDL,
  ...MCE_SQL_PROHIBITED_PROCEDURAL,
]);

export const MCE_SQL_UNSUPPORTED_FUNCTIONS = new Map<string, string | null>([
  ["string_split", null],
  ["json_modify", null],
  ["openjson", null],
  ["isjson", null],
  ["try_convert", "Use CONVERT() instead"],
  ["try_cast", "Use CAST() instead"],
  ["try_parse", null],
]);

export const MCE_SQL_SUPPORTED_FUNCTIONS = new Set([
  // String functions
  "left",
  "right",
  "len",
  "charindex",
  "patindex",
  "concat",
  "ltrim",
  "rtrim",
  "trim",
  "lower",
  "upper",
  "newid",
  "format",
  "substring",
  "replace",
  "stuff",
  "reverse",
  "replicate",
  "space",
  "str",
  "char",
  "ascii",
  "nchar",
  "unicode",
  // Date functions
  "getdate",
  "getutcdate",
  "datepart",
  "datename",
  "year",
  "month",
  "day",
  "datefromparts",
  "datetimefromparts",
  "dateadd",
  "datediff",
  "eomonth",
  "isdate",
  "sysdatetime",
  "sysutcdatetime",
  "sysdatetimeoffset",
  "switchoffset",
  "todatetimeoffset",
  // Numeric/aggregate functions
  "min",
  "max",
  "avg",
  "sum",
  "count",
  "string_agg",
  "abs",
  "ceiling",
  "floor",
  "round",
  "sign",
  "sqrt",
  "square",
  "power",
  "exp",
  "log",
  "log10",
  "rand",
  "pi",
  "sin",
  "cos",
  "tan",
  "asin",
  "acos",
  "atan",
  "atan2",
  "cot",
  "degrees",
  "radians",
  "stdev",
  "stdevp",
  "var",
  "varp",
  // Conversion functions
  "cast",
  "convert",
  // NULL handling functions
  "isnull",
  "coalesce",
  "nullif",
  // Conditional functions
  "iif",
  // JSON functions (supported in SQL Server 2016+)
  "json_value",
  "json_query",
  // Other functions
  "checksum",
  "row_number",
  "rank",
  "dense_rank",
  "ntile",
  "lead",
  "lag",
  "first_value",
  "last_value",
  "percent_rank",
  "cume_dist",
  "percentile_cont",
  "percentile_disc",
]);

export const MCE_SQL_DATA_TYPES = new Set([
  // Exact numerics
  "bigint",
  "int",
  "integer",
  "smallint",
  "tinyint",
  "bit",
  "decimal",
  "numeric",
  "money",
  "smallmoney",
  // Approximate numerics
  "float",
  "real",
  // Date and time
  "date",
  "datetime",
  "datetime2",
  "datetimeoffset",
  "smalldatetime",
  "time",
  // Character strings
  "char",
  "varchar",
  "text",
  // Unicode character strings
  "nchar",
  "nvarchar",
  "ntext",
  // Binary strings
  "binary",
  "varbinary",
  "image",
  // Other data types
  "uniqueidentifier",
  "xml",
  "sql_variant",
]);

export const MCE_SQL_OPERATORS = new Set([
  "=",
  "!=",
  "<>",
  "<",
  ">",
  "<=",
  ">=",
  "+",
  "-",
  "*",
  "/",
  "%",
]);
